sudo: false
dist: focal
addons:
  apt:
    packages:
    - texlive-base
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-latex-extra
    - texlive-formats-extra
    - texlive-bibtex-extra
    - texlive-humanities
    - texinfo
    - texlive-science
    - latexmk
    - lmodern
    - biber
script:
- pip install -r requirements.txt
- BOOK_VERSION=$(./get-current-version.sh) travis-sphinx build -n -s source
after_success:
- travis-sphinx deploy --cname yhlu.net
before_deploy:
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - ./**/*.pdf
    - ./**/*.epub
  skip_cleanup: true
  on:
    repo: luyunghsiang/yhluweb
    tags: true
